#!/bin/sh
basedir=`dirname "$0"`

case `uname` in
    *CYGWIN*) basedir=`cygpath -w "$basedir"`;;
esac

if [ -x "$basedir/bash" ]; then
  "$basedir/bash"  "$basedir/node_modules/n/bin/n" "$@"
  ret=$?
else 
  bash  "$basedir/node_modules/n/bin/n" "$@"
  ret=$?
fi
exit $ret
